"""add character portrait

Revision ID: 4fefd1c6a430
Revises: ccf4cbd117bf
Create Date: 2026-08-13 12:03:38.467021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fefd1c6a430'
down_revision: Union[str, Sequence[str], None] = 'ccf4cbd117bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('portrait_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'portrait_url')
    # ### end Alembic commands ###
