"""add character proficiencies

Revision ID: 8ac7a454b8db
Revises: c84edf0a45db
Create Date: 2026-08-09 14:57:32.446674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac7a454b8db'
down_revision: Union[str, Sequence[str], None] = 'c84edf0a45db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('saving_throw_proficiencies', sa.JSON(), nullable=False))
    op.add_column('characters', sa.Column('skill_proficiencies', sa.JSON(), nullable=False))
    op.add_column('characters', sa.Column('spellcasting_ability', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'spellcasting_ability')
    op.drop_column('characters', 'skill_proficiencies')
    op.drop_column('characters', 'saving_throw_proficiencies')
    # ### end Alembic commands ###
