"""add character hit points

Revision ID: 8e5c1648e8cf
Revises: 8ac7a454b8db
Create Date: 2026-08-11 18:43:34.790211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5c1648e8cf'
down_revision: Union[str, Sequence[str], None] = '8ac7a454b8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('maximum_hp', sa.Integer(), server_default='1', nullable=False))
    op.add_column('characters', sa.Column('current_hp', sa.Integer(), server_default='1', nullable=False))
    op.add_column('characters', sa.Column('temporary_hp', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint(
        "ck_characters_maximum_hp",
        "characters",
        "maximum_hp > 0",
    )
    op.create_check_constraint(
        "ck_characters_current_hp",
        "characters",
        "current_hp BETWEEN 0 AND maximum_hp",
    )
    op.create_check_constraint(
        "ck_characters_temporary_hp",
        "characters",
        "temporary_hp >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_characters_temporary_hp",
        "characters",
        type_="check",
    )
    op.drop_constraint(
        "ck_characters_current_hp",
        "characters",
        type_="check",
    )
    op.drop_constraint(
        "ck_characters_maximum_hp",
        "characters",
        type_="check",
    )
    op.drop_column('characters', 'temporary_hp')
    op.drop_column('characters', 'current_hp')
    op.drop_column('characters', 'maximum_hp')
    # ### end Alembic commands ###
