"""add character species and background

Revision ID: c1bb6a8b6e12
Revises: 4fefd1c6a430
Create Date: 2026-08-18 18:34:55.374782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bb6a8b6e12'
down_revision: Union[str, Sequence[str], None] = '4fefd1c6a430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('species', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('background', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'background')
    op.drop_column('characters', 'species')
    # ### end Alembic commands ###
