"""create characters table

Revision ID: c84edf0a45db
Revises: b0da1f2c1e3d
Create Date: 2026-08-09 14:07:51.801762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84edf0a45db'
down_revision: Union[str, Sequence[str], None] = 'b0da1f2c1e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('character_class', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.SmallInteger(), nullable=False),
    sa.Column('dexterity', sa.SmallInteger(), nullable=False),
    sa.Column('constitution', sa.SmallInteger(), nullable=False),
    sa.Column('intelligence', sa.SmallInteger(), nullable=False),
    sa.Column('wisdom', sa.SmallInteger(), nullable=False),
    sa.Column('charisma', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            strength BETWEEN 1 AND 20\n            AND dexterity BETWEEN 1 AND 20\n            AND constitution BETWEEN 1 AND 20\n            AND intelligence BETWEEN 1 AND 20\n            AND wisdom BETWEEN 1 AND 20\n            AND charisma BETWEEN 1 AND 20\n            ', name='ck_characters_ability_scores'),
    sa.CheckConstraint('level BETWEEN 1 AND 5', name='ck_characters_level'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
