"""create resources table

Revision ID: ccf4cbd117bf
Revises: 8e5c1648e8cf
Create Date: 2026-08-11 19:00:04.058097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf4cbd117bf'
down_revision: Union[str, Sequence[str], None] = '8e5c1648e8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('recovery_type', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            recovery_type IN (\n                'SHORT_REST',\n                'LONG_REST',\n                'MANUAL'\n            )\n            ", name='ck_resources_recovery_type'),
    sa.CheckConstraint('current BETWEEN 0 AND maximum', name='ck_resources_current'),
    sa.CheckConstraint('maximum > 0', name='ck_resources_maximum'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_character_id'), 'resources', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_character_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
